# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OCDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

flutter_application_path = '../../Flutter_Demo/flutter_module_demo/'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

install_all_flutter_pods(flutter_application_path)

  # Pods for OCDemo

  target 'OCDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'OCDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
